      - name: Generate WRSGwiggle Environment
        run: |
          mkdir out
          cp index.doctor out/
          echo '<script src="https://jsdelivr.net"></script>' > out/index.html
          echo '<wrsg-wiggle src="index.doctor"></wrsg-wiggle>' >> out/index.html
          echo '<doggy-engine src="https://jsdelivr.net"></doggy-engine>' >> out/index.html
          echo '<script src="https://jsdelivr.net"></script>' >> out/index.html
          
          # AUTOMATED THEME STITCHER (Leaves all core code and contents untouched)
          cat append.html >> out/index.html
